### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by venky-anubavam** [rborn/TitaniumYoutubePlayer#2]
Ti.Network.createHTTPClient - It goes to onerror Callback - error {"type":"error","source":{"cache":false},"code":404,"error":"HTTP error","success":false}

**Comment by rborn** [comment]
Give me more details, platform? Ti SDK, maybe you try to get a wrong video?

**Comment by venky-anubavam** [comment]
Ti SDK - 3.1.0
IOS - 6.1

Video url running in webview and also running in safari.
Now not running in your Application.. Its also getting same error. Previously it was working in my application and your application

**Comment by rborn** [comment]
Something changed on the YouTube side, looking for a fix

**Comment by venky-anubavam** [comment]
Thanks in advance. notice me once fixed

**Comment by rborn** [comment]
Please have a look now, didn't have time to test it on Android.
Let me know if you test it on android and if it works or not.

Thank you.

**Comment by venky-anubavam** [comment]
Great its working fine now.

Can you please provide me what changes made in YouTube. Where you got those information.

**Comment by rborn** [comment]
They changed the layout, so the old code couldn't find the info anymore.
Read the Update section in the readme file to see what I changed

**Comment by venky-anubavam** [comment]
Thanks for your information.
